Added Page Breaks
salvois/LargeXlsx pull request #57
Opened 2024-11-11 09:31 UTC by thedude61636

I've added page breaks 

public XlsxWriter AddPageBreak(); //adds a page break at the current index and column
public XlsxWriter AddRowPageBreak(); //adds a horizontal page break at the current row
public XlsxWriter AddColumnPageBreak(); //adds a vertical page break at the current column

2024-11-24 09:11 UTC, salvois commented
Hi @thedude61636 ,
thanks for your contribution! I hope I can have a look in the weekend.

2024-11-24 16:48 UTC, salvois requested changes

2024-12-01 11:47 UTC, thedude61636 commented on src/LargeXlsx/Worksheet.cs
> +        private readonly List<int> _rowBreaks;
Alright makes sense

2024-12-01 11:54 UTC, thedude61636 commented on src/LargeXlsx/Worksheet.cs
> +                    _streamWriter.Write($"<brk id=\"{rowNum}\" max=\"16383\" man=\"1\"/>");
alright but max column count is private in that class we either make it public or move it to this class or we can make a constants class and put the max row and column count there , it's kinda weird having the max row count in the worksheet and the max column count in util

2024-12-01 12:05 UTC, thedude61636 commented on src/LargeXlsx/XlsxWriter.cs
> +        public XlsxWriter AddPageBreak()
you're right it does sound confusing 
i can remove all the methods and make two methods (one for horizontal and one for vertical) that takes a default value if it's null it inserts at insertion point and if not, it inserts at specified value

and that's alright nitpick all you want :D

2025-02-02 09:41 UTC, salvois commented
Hi @thedude61636 ,
this pull request is open for a while, so I'm assuming you had more compelling tasks to do (and rightfully so of course!).
If you agree, I'd inherit the code from this pull request and change it as proposed, so that I can try to have the feature in the library.
Thanks,
   Salvo

2025-02-02 09:52 UTC, thedude61636 commented
I'm sorry I'm a bit busy with life and didn't have much time to complete this, if you want to complete it go ahead :)

2025-03-15 10:03 UTC, merged